# ASP.NET Core

trigger:
  batch: true
  branches:
    include:
    - master
  #Required if using multiple yaml files in one repository.  
  #paths:
  #  include:
  #  - 'src/WebApplication1'

resources:
  repositories:
    - repository: Pipelines
      type: git
      name: IT/Pipelines

variables:
  applicationName: 'Clean Architecture'

extends:
  template: webTemplate.yml@Pipelines
  parameters:
    applicationName: '${{ variables.ApplicationName }}' # Required - Name of the deployed site. Example: 'WebStart' is deployed out as dev.polkcountyiowa.gov/WebStart
     #solution: '**/*.sln' - Target a specific solution in the repository. Example: '**/PolkCounty.WebStart.sln'.
     #buildConfiguration: Release - Options: Release, Debug
     #pool: Default - Options: Default
     #publishProjects: '' - Required if using multiple yaml files in one repository. Example: '**/PolkCounty.WebStart.csproj'.